### ISSUE TITLE
what we need for bulid ? 

### ISSUE THREAD

**Issue by Coinpiet** [nikitaneo/rho_pollard#2]
Hello i try to bulid this programm i have gtest installed. 

but i always get this build error 
`/usr/local/cuda-10.0/bin/nvcc test/test.cu -o bin/test -O3 -lgtest -lgtest_main -L/usr/lib -lpthread -std=c++11 -ccbin /usr/bin/g++-5 -Wno-deprecated-gpu-targets -I /usr/local/include/gtest -I include
/usr/bin/ld: Ausgabedatei  bin/test: Datei oder Verzeichnis nicht gefunden kann nicht geöffnet werden
collect2: error: ld returned 1 exit status
Makefile:9: die Regel für Ziel „opt“ scheiterte
make: *** [opt] Fehler 1
`

mabey you can help a bit ?

**Comment by nikitaneo** [comment]
Hi,

I've updated README with info about dependencies, please take a look.

**Comment by nikitaneo** [comment]
Also, please notice that "bin" folder should exist in the root of the project.
