### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by hamnaz** [nikitaneo/rho_pollard#3]
#include <gtest/gtest.h>
gtest not exist

make
/usr/local/cuda-8.0/bin/nvcc test/test.cu -o bin/test -O3 -lgtest -lgtest_main -L/usr/lib -lpthread -std=c++11 -ccbin /usr/bin/g++-4.8 -Wno-deprecated-gpu-targets -I /usr/local/include/gtest -I include
test/test.cu:1:25: fatal error: gtest/gtest.h: No such file or directory

**Comment by nikitaneo** [comment]
You need Google Test library installed in your system. Please follow the instructions here: https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/

**Comment by hamnaz** [comment]
make
/usr/local/cuda-8.0/bin/nvcc test/test.cu -o bin/test -O3 -lgtest -lgtest_main -                         L/usr/lib -lpthread -std=c++11 -ccbin /usr/bin/g++-4.8 -Wno-deprecated-gpu-targe                         ts -I /usr/local/include/gtest -I include
/tmp/tmpxft_000020da_00000000-16_test.o: In function `base_uint_arithmetics_Test                         ::TestBody()':
tmpxft_000020da_00000000-4_test.cudafe1.cpp:(.text+0x4aad): undefined reference                          to `testing::internal::EqFailure(char const*, char const*, std::string const&, s                         td::string const&, bool)'
/tmp/tmpxft_000020da_00000000-16_test.o: In function `bits10_curve_gpu_Test::Tes                         tBody()':
tmpxft_000020da_00000000-4_test.cudafe1.cpp:(.text+0x650b): undefined reference                          to `testing::internal::EqFailure(char const*, char const*, std::string const&, s                         td::string const&, bool)'
/tmp/tmpxft_000020da_00000000-16_test.o: In function `bits10_curve_cpu_Test::Tes                         tBody()':
tmpxft_000020da_00000000-4_test.cudafe1.cpp:(.text+0x66fb): undefined reference                          to `testing::internal::EqFailure(char const*, char const*, std::string const&, s                         td::string const&, bool)'
/tmp/tmpxft_000020da_00000000-16_test.o: In function `bits35_curve_cpu_Test::Tes                         tBody()':
tmpxft_000020da_00000000-4_test.cudafe1.cpp:(.text+0x6a2b): undefined reference                          to `testing::internal::EqFailure(char const*, char const*, std::string const&, s                         td::string const&, bool)'
/tmp/tmpxft_000020da_00000000-16_test.o: In function `bits35_curve_gpu_Test::Tes                         tBody()':
tmpxft_000020da_00000000-4_test.cudafe1.cpp:(.text+0x6d5b): undefined reference                          to `testing::internal::EqFailure(char const*, char const*, std::string const&, s                         td::string const&, bool)'
/tmp/tmpxft_000020da_00000000-16_test.o:tmpxft_000020da_00000000-4_test.cudafe1.                         cpp:(.text._ZN7testing8internal11CmpHelperEQI9base_uintILj4EES3_EENS_15Assertion                         ResultEPKcS6_RKT_RKT0_[_ZN7testing8internal11CmpHelperEQI9base_uintILj4EES3_EENS                         _15AssertionResultEPKcS6_RKT_RKT0_]+0x83): more undefined references to `testing                         ::internal::EqFailure(char const*, char const*, std::string const&, std::string                          const&, bool)' follow
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'opt' failed
make: *** [opt] Error 1
